services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - data-volume:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    user: appuser

volumes:
  data-volume:
    driver: local